### PR TITLE
Added sconverting Posix to str in get_ontology

### PR DESCRIPTION
**Pull request by francescalb**
# Description:

get_ontology would fail if given a valid pathlib.Posix

## Type of change:

- [x] Bug fix.
- [ ] New feature.
- [ ] Documentation update.

## Checklist:

This checklist can be used as a help for the reviewer.

- [ ] Is the code easy to read and understand?
- [ ] Are comments for humans to read, not computers to disregard?
- [ ] Does a new feature has an accompanying new test (in the CI or unit testing schemes)?
- [ ] Has the documentation been updated as necessary?
- [ ] Does this close the issue?
- [ ] Is the change limited to the issue?
- [ ] Are errors handled for all outcomes?
- [ ] Does the new feature provide new restrictions on dependencies, and if so is this documented?

### CODE REVIEW

**Review by CasperWA — COMMENTED** [review]
Is this true only for `PosixPath` or can the more general `pathlib.Path` be used, which will "turn into" a `PosixPath` on a POSIX system and a Windows-specific `Path` on a Windows system, etc.?

Maybe one should also instead use the `as_uri()` instead of casting to a `str`?

**Comment by francescalb** [comment]
> Is this true only for `PosixPath` or can the more general `pathlib.Path` be used, which will "turn into" a `PosixPath` on a POSIX system and a Windows-specific `Path` on a Windows system, etc.?
> 
> Maybe one should also instead use the `as_uri()` instead of casting to a `str`?

Good point. I ha dnot thought about windows. Indeed the whole test fails on windows already in the master ...

**Comment by CasperWA** [comment]
> (...) Indeed the whole test fails on windows already in the master ...

How do you know? Did you test locally?

**Review by CasperWA — APPROVED** [review]
Approved on the condition that an issue is created for the Windows-issue, which may be solved by implementing a dedicated class that incorporates `pathlib.Path` as well as URLs.

**Pull request merged**
