### PR TITLE
Support use of skos:prefLabel instead of rdfs:label

### PR DESCRIPTION
**Pull request by jesper-friis**
This is still work in progress and has to be tested better.

### CODE REVIEW

**Review by francescalb — COMMENTED** [review]
Seems to be working correctly

**Comment by jesper-friis** [comment]
Thanks for fast feedback. Some tests are failing, though, most are due to duplicated declerations of Inductance and CatalyticActivity. They are now removed in EMMO PR #93. 

The last failure is in emmo/ontodoc.py:241

**Comment by francescalb** [comment]
Next problem is with get_annotations in emmo/ontology.py.
With altLabel it returns a dicionary key None (InternalEnergy.get_annotations)
Note that I had to remake emmo-inferred in EMMO PR 93 locally.

**Comment by francescalb** [comment]
> Next problem is with get_annotations in emmo/ontology.py.
> With altLabel it returns a dicionary key None (InternalEnergy.get_annotations)
> Note that I had to remake emmo-inferred in EMMO PR 93 locally.

Still have problems with the inferred ontology. I pushed my emmo-inferred.owl to PR93
and tested loading the ontology
get_ontology('path/to/local/emmo-inferred.owl') works well

get_ontology('https://github.com/emmo-repo/EMMO/blob/add-additional-quantities/emmo-inferred.owl') fails in the RDF/XML parsing.

**Review by francescalb — APPROVED** [review]
This is now working well.

**Pull request merged**
