### PR TITLE
Fix checking PR body & improve error message in CD

### LINKED ISSUE #319: Edge-case fails CD workflow for dependabot
An edge-case can cause the CD workflow that updates the `ci/dependabot-updates` branch after a release to fail.
This issue was originally reported in Materials-Consortia/optimade-python-tools#995, where similar workflows are used.

### PR DESCRIPTION
**Pull request by CasperWA**
# Description:

There is a minor edge-case where the CD will fail updating the `ci/dependabot-updates` branch (upon a release), this minor fix sorts out that issue.
(This edge-case was found in [Materials-Consortia/optimade-python-tools](https://github.com/Materials-Consortia/optimade-python-tools) where similar workflows are used.)

Fixes #319.

It also adds a more informative error message for what steps to do next if the CD workflow fails in a particular step.

## Type of change:

- [X] Bug fix.
- [ ] New feature.
- [X] Documentation update.

## Checklist:

This checklist can be used as a help for the reviewer.

- [ ] Is the code easy to read and understand?
- [ ] Are comments for humans to read, not computers to disregard?
- [ ] Does a new feature has an accompanying new test (in the CI or unit testing schemes)?
- [ ] Has the documentation been updated as necessary?
- [ ] Does this close the issue?
- [ ] Is the change limited to the issue?
- [ ] Are errors handled for all outcomes?
- [ ] Does the new feature provide new restrictions on dependencies, and if so is this documented?

### CODE REVIEW

**Comment by francescalb** [comment]
Is there a method to test this?

**Comment by CasperWA** [comment]
> Is there a method to test this?

The way I tested it originally was locally, to see which method would work - using the [gh cli](https://cli.github.com/) to download particular PR body texts and testing different ways to format it and comparisons in order to ensure that the logic here works.
Essentially the text _will_ be changed once someone clicks the checkboxes - and I think there are some other changes happening automatically if someone accidentally "edits" the body - even without changing anything. The latter is the edge case I suspect happened in the other repository, where the current solution didn't work. This one seems to have been working so far in the other repository :)

**Comment by francescalb** [comment]
> > Is there a method to test this?
> 
> The way I tested it originally was locally, to see which method would work - using the [gh cli](https://cli.github.com/) to download particular PR body texts and testing different ways to format it and comparisons in order to ensure that the logic here works. Essentially the text _will_ be changed once someone clicks the checkboxes - and I think there are some other changes happening automatically if someone accidentally "edits" the body - even without changing anything. The latter is the edge case I suspect happened in the other repository, where the current solution didn't work. This one seems to have been working so far in the other repository :)

Thank you for the explanation. Then I think it is safe and good to go with this here as well-

**Review by francescalb — APPROVED** [review]
good

**Pull request merged**
