### PR TITLE
Use width in img HTML

### LINKED ISSUE #233: Fix images in documentation
The logos in the documentation landing page should be similar in size to the ones in the GitHub README.

### PR DESCRIPTION
**Pull request by CasperWA**
# Description:

Update in README.md and used `inv create-docs-index` to update the index.md in the documentation.

Fixes #233.

## Type of change:

- [X] Bug fix.
- [ ] New feature.
- [X] Documentation update. (kind of)

## Checklist:

This checklist can be used as a help for the reviewer.

- [ ] Is the code easy to read and understand?
- [ ] Are comments for humans to read, not computers to disregard?
- [ ] Does a new feature has an accompanying new test (in the CI or unit testing schemes)?
- [ ] Has the documentation been updated as necessary?
- [ ] Does this close the issue?
- [ ] Is the change limited to the issue?
- [ ] Are errors handled for all outcomes?
- [ ] Does the new feature provide new restrictions on dependencies, and if so is this documented?

## Comments:

In order to test this locally do the following:

```console
$ git fetch origin && git branch cwa/fix-233-doc-images origin/cwa/fix-233-doc-images && git checkout cwa/fix-233-doc-images
$ pip install -U -e .[docs]
$ mkdocs serve
```

Then go to: [http://127.0.0.1:8000/EMMO-python](http://127.0.0.1:8000/EMMO-python) and scroll down to see that the images are nicely sized now.

### CODE REVIEW

**Review by francescalb — APPROVED** [review]
Very good, looks nice now :) (Should we try to have index.md and README.md reading info about contributing projects from one common place?)

**Comment by CasperWA** [comment]
> Very good, looks nice now :) (Should we try to have index.md and README.md reading info about contributing projects from one common place?)

What do you mean exactly by this?

As it is now:
`README.md` is the "source" and `index.md` is "generated" using the `invoke` task `create-docs-index`.
This task essentially copies the `README.md` file, renames it, and fixes the relative links in the file.
`index.md` is _only_ used in the documentation, while `README.md` is _only_ used/presented on GitHub - and serves as the local README file as well, of course :)

So the "one common place" (even though it doesn't seem like it) is indeed the `README.md` file.

But if you mean that we can have a dedicated documentation page about the contributing projects, then, yes! That's a great idea :)

**Comment by francescalb** [comment]
> > Very good, looks nice now :) (Should we try to have index.md and README.md reading info about contributing projects from one common place?)
> 
> What do you mean exactly by this?
> 
> As it is now: `README.md` is the "source" and `index.md` is "generated" using the `invoke` task `create-docs-index`. This task essentially copies the `README.md` file, renames it, and fixes the relative links in the file. `index.md` is _only_ used in the documentation, while `README.md` is _only_ used/presented on GitHub - and serves as the local README file as well, of course :)
> 
> So the "one common place" (even though it doesn't seem like it) is indeed the `README.md` file.
> 
> But if you mean that we can have a dedicated documentation page about the contributing projects, then, yes! That's a great idea :)

Ah, I see. I just looked at the 'Files changed' here and saw that both were changed. I did not realise that the index.md is generated from the README.md.

**Comment by CasperWA** [comment]
> Ah, I see. I just looked at the 'Files changed' here and saw that both were changed. I did not realise that the index.md is generated from the README.md.

Yeah, no worries.
The actual auto-generation will be implemented as part of #232.

**Pull request merged**
