### PR TITLE
Fixed link to OpenModel logo

### LINKED ISSUE #278: OpenModel logo not loading in README

### PR DESCRIPTION
**Pull request by francescalb**
# Description:

Fixed link to OpenModel logo in README.md
Closes #278 

## Type of change:

- [x] Bug fix.
- [ ] New feature.
- [x] Documentation update.

## Checklist:

This checklist can be used as a help for the reviewer.

- [ ] Is the code easy to read and understand?
- [ ] Are comments for humans to read, not computers to disregard?
- [ ] Does a new feature has an accompanying new test (in the CI or unit testing schemes)?
- [ ] Has the documentation been updated as necessary?
- [ ] Does this close the issue?
- [ ] Is the change limited to the issue?
- [ ] Are errors handled for all outcomes?
- [ ] Does the new feature provide new restrictions on dependencies, and if so is this documented?

### CODE REVIEW

**Comment by CasperWA** [comment]
See [here](https://github.com/emmo-repo/EMMO-python/runs/4071639763?check_suite_focus=true#step:6:21): You must run `invoke create-docs-index` and git add and commit the updated `docs/index.md` file :)

**Comment by CasperWA** [comment]
Note, if the `invoke` command doesn't work, remember to install the "docs" extra for this repository, i.e., `pip install -e .[docs]` :)

**Comment by francescalb** [comment]
I had completely forgotten :(  Fixed now I think.

**Comment by CasperWA** [comment]
> I had completely forgotten :( Fixed now I think.

No worries - this is why we have the CI :) It also tells you what to do, I just reiterated it here as a comment.

**Review by CasperWA — APPROVED** [review]
Great ! Seems to come through as it should. Thanks @francescalb 🚀

**Pull request merged**
