### PR TITLE
When visualising restrictions, annotate the edges with the restriction type by default

### PR DESCRIPTION
**Pull request by jesper-friis**
Used to produce the graphs for the updated README for EMMO 1.0.0-beta3:
https://github.com/emmo-repo/EMMO/tree/updated-readme-and-figures

# Description:

## Type of change:

- [ ] Bug fix.
- [x] New feature.
- [ ] Documentation update.

## Checklist:

This checklist can be used as a help for the reviewer.

- [ ] Is the code easy to read and understand?
- [ ] Are comments for humans to read, not computers to disregard?
- [ ] Does a new feature has an accompanying new test (in the CI or unit testing schemes)?
- [ ] Has the documentation been updated as necessary?
- [ ] Does this close the issue?
- [ ] Is the change limited to the issue?
- [ ] Are errors handled for all outcomes?
- [ ] Does the new feature provide new restrictions on dependencies, and if so is this documented?

### CODE REVIEW

**Comment by jesper-friis** [comment]
The CI workflow fails with an internal [error](https://github.com/emmo-repo/EMMO-python/runs/4669272237?check_suite_focus=true#step:7:1320). Running it locally works fine:

```
$ mkdocs build --strict 
INFO     -  Cleaning site directory
INFO     -  Building documentation to directory:
            /home/friisj/prosjekter/EMMC/EMMO-python/site
INFO     -  Documentation built in 2.79 seconds
$ mkdocs --version
mkdocs, version 1.2.3 from /home/friisj/.local/lib/python3.9/site-packages/mkdocs (Python 3.9)
```

Looks more like a bug in mkdocs than in EMMOntoPy...

**Review by CasperWA — APPROVED** [review]
Seems fine to me - although some of it goes a bit beyond my knowledge :)

**Review by francescalb — CHANGES_REQUESTED** [review]
image

As of now hasConstituent, hasProperPArt and has SpatialEssentialPArt are the same. As suggest that at least has Consituent and hasSpatialPart get their own colors. Furthermore, I also think it makes sense to add the label if the revert to the default color.

**Comment by jesper-friis** [comment]
> As of now hasConstituent, hasProperPArt and has SpatialEssentialPArt are the same. As suggest that at least has Consituent and hasSpatialPart get their own colors. Furthermore, I also think it makes sense to add the label if the revert to the default color.

I agree that it would be a good idea to review the default colours and styles. But I think EMMO has too many relations to give all of them a unique default colour/style combination. One possibility could be to make mereological, topological and semiotical relations solid, dashed and dotted respectively. For colours we could either
- leave it to the user to define them for each plot
- define explicit colours for some high-level/important relations within each category
- define a colour cycle and more or less randomly assign them to the relations present in the graph (pros: all relations will get a unique colour by default; cons: the same relation may get different colours in two different graphs)

I think this should be a new issue.

**Comment by francescalb** [comment]
> > As of now hasConstituent, hasProperPArt and has SpatialEssentialPArt are the same. As suggest that at least has Consituent and hasSpatialPart get their own colors. Furthermore, I also think it makes sense to add the label if the revert to the default color.
> 
> I agree that it would be a good idea to review the default colours and styles. But I think EMMO has too many relations to give all of them a unique default colour/style combination. One possibility could be to make mereological, topological and semiotical relations solid, dashed and dotted respectively. For colours we could either
> 
> * leave it to the user to define them for each plot
> * define explicit colours for some high-level/important relations within each category
> * define a colour cycle and more or less randomly assign them to the relations present in the graph (pros: all relations will get a unique colour by default; cons: the same relation may get different colours in two different graphs)
> 
> I think this should be a new issue.

Ok, then I think this PR can be approved.

**Review by francescalb — APPROVED** [review]

**Pull request merged**
